language: go
go:
- 1.5
sudo: false
services:
- memcache
- redis-server
- postgresql
before_script:
- psql -c 'create user ladybug;' -U postgres
- psql -c 'create database ladybug;' -U postgres
- psql -c 'ALTER DATABASE ladybug OWNER TO ladybug;' -U postgres
- npm install -g bower
- bower install jquery bootstrap bootstrap-sweetalert datatables iCheck ladda 
install:
- export PATH=$PATH:$HOME/gopath/bin
- go get -v gopkg.in/fsnotify.v1
- go get -v github.com/gorilla/mux
- go get -v github.com/gorilla/sessions
- go get -v github.com/gorilla/schema
- go get -v github.com/jinzhu/gorm
- go get -v github.com/lib/pq
- go get -v golang.org/x/crypto/bcrypt
- go get -v gopkg.in/inconshreveable/log15.v2
- go get -v github.com/robfig/config


notifications:
  slack: ladybugdev:dGWtXjXTstY63pMo2yLvvOHy
