language: go
go:
- 1.5
sudo: false
services:
- memcache
- redis-server
- postgresql
before_script:
- psql -c 'create user ladybug;' -U postgres
- psql -c 'create database ladybug;' -U postgres
- psql -c 'ALTER DATABASE ladybug OWNER TO ladybug;' -U postgres
- npm install -g bower
- bower install  
install:
- export PATH=$PATH:$HOME/gopath/bin
- go get -t -d -v ./...
    
notifications:
  slack: ladybugdev:dGWtXjXTstY63pMo2yLvvOHy
